package by.epam.project.command;

public enum CommandType {
    LOGIN,
    LOGOUT,

    UPDATE_BALANCE,
    REFRESH_BALANCE,

    ADD_CAR,
    UPDATE_CAR,
    REQUEST_RENT_CAR,
    DELETE_CAR,
    TAKE_RENTED_CARS,
    TAKE_NOT_RENTED_CARS,

    ACCEPT_ORDER,
    DENY_ORDER,
    DELETE_ORDER,
    ADD_ORDER_INFO,
    ADD_AD_SERVICE_PRICE,
    PAY_AD_SERVICE_PRICE,
    TAKE_PAID_ORDERS,
    TAKE_NOT_PAID_ORDERS,
    TAKE_ORDER_BY_EMAIL,

    SET_LANG_JS_MESSAGE

}
